### PR TITLE
Add parameter to control access log

### PR DESCRIPTION
**Pull request by jacksgt**

### CODE REVIEW

**Review by martialblog — APPROVED** [review]
Does it update the service automatically when the file changes?

**Comment by jacksgt** [comment]
@martialblog Is there a smart way to mock the `exec` resource in the beaker tests?

**Comment by martialblog** [comment]
Hm maybe... I know we mocked some function calls here, but that was spec: https://github.com/vision-it/vision-icinga2/blob/production/spec/classes/server_spec.rb

**Comment by martialblog** [comment]
@jacksgt I mean, you could also mock /usr/bin/docker :bird:

**Comment by jacksgt** [comment]
> @jacksgt I mean, you could also mock /usr/bin/docker bird

How would I copy /bin/true to /usr/bin/docker with Beaker (Ruby)?

**Comment by jacksgt** [comment]
Seems to work like this (see last commit), what do you think? @martialblog

**Comment by martialblog** [comment]
Looks good!On 20 Sep 2019 10:19 am, Jack Henschel <notifications@github.com> wrote:Seems to work like this (see last commit), what do you think? @martialblog

**Comment by jacksgt** [comment]
Thanks for the feedback!

**Pull request merged**
